version: '3.8'

services:
  radio:
    build: .
    container_name: radioresurrector
    restart: unless-stopped
    environment:
      - STREAM_URL=https://ice5.somafm.com/live-128-mp3
      - CHUNK_SECONDS=300
      - BUFFER_MINUTES=120
      - CHECK_INTERVAL=10
    volumes:
      - ./buffer:/opt/radio/buffer
    devices:
      - /dev/snd:/dev/snd
    privileged: true
