#!/usr/bin/env python3
"""RadioResurrector Web Interface"""

import json
import os
import secrets
import subprocess
import time

from flask import Flask, jsonify, redirect, render_template_string, request, session, url_for

BASE_DIR = "/opt/radio"
CONFIG_FILE = os.path.join(BASE_DIR, "config.json")
CONFIG_SH = os.path.join(BASE_DIR, "config.sh")
BUFFER_DIR = os.path.join(BASE_DIR, "buffer")
STATE_FILE = os.path.join(BASE_DIR, "state.json")

app = Flask(__name__)

DEFAULT_CONFIG = {
    "secret_key": secrets.token_hex(32),
    "pin": "1234",
    "stream_url": "https://findyourownstream.example/stream",
    "chunk_seconds": 300,
    "buffer_minutes": 120,
    "check_interval": 10,
    "volume": 90,
    "streams": [
        {"name": "Example Stream", "url": "https://findyourownstream.example/stream"}
    ],
}


def load_config():
    if not os.path.exists(CONFIG_FILE):
        save_config(DEFAULT_CONFIG)
        return DEFAULT_CONFIG
    with open(CONFIG_FILE) as f:
        return json.load(f)


def save_config(cfg):
    with open(CONFIG_FILE, "w") as f:
        json.dump(cfg, f, indent=2)
    write_shell_config(cfg)


def write_shell_config(cfg):
    with open(CONFIG_SH, "w") as f:
        f.write("# Auto-generated by RadioResurrector web interface — do not edit manually\n")
        f.write(f'STREAM_URL="{cfg["stream_url"]}"\n')
        f.write(f'CHUNK_SECONDS={cfg["chunk_seconds"]}\n')
        f.write(f'BUFFER_MINUTES={cfg["buffer_minutes"]}\n')
        f.write(f'MAX_CHUNKS=$(( BUFFER_MINUTES * 60 / CHUNK_SECONDS ))\n')
        f.write(f'CHECK_INTERVAL={cfg["check_interval"]}\n')
        f.write(f'VOLUME={cfg["volume"]}\n')


def service_status():
    try:
        r = subprocess.run(
            ["systemctl", "is-active", "radio.service"],
            capture_output=True, text=True, timeout=5,
        )
        return r.stdout.strip()
    except Exception:
        return "unknown"


def playback_state():
    """Read the state.json written by radio.sh."""
    try:
        with open(STATE_FILE) as f:
            return json.load(f)
    except Exception:
        return {"mode": "unknown", "url": "", "since": 0}


def buffer_info():
    """Return stats and file list for the buffer directory."""
    cfg = load_config()
    chunk_seconds = cfg.get("chunk_seconds", 300)
    max_chunks = cfg.get("buffer_minutes", 120) * 60 // chunk_seconds

    try:
        files = sorted(
            [f for f in os.listdir(BUFFER_DIR) if f.endswith(".mp3")],
        )
    except Exception:
        files = []

    file_details = []
    total_bytes = 0
    oldest_ts = None
    newest_ts = None

    for name in files:
        path = os.path.join(BUFFER_DIR, name)
        try:
            st = os.stat(path)
            sz = st.st_size
            mt = int(st.st_mtime)
        except OSError:
            continue
        total_bytes += sz
        if oldest_ts is None or mt < oldest_ts:
            oldest_ts = mt
        if newest_ts is None or mt > newest_ts:
            newest_ts = mt
        file_details.append({"name": name, "size": sz, "mtime": mt})

    covers_seconds = len(file_details) * chunk_seconds

    return {
        "files": file_details,
        "chunk_count": len(file_details),
        "max_chunks": max_chunks,
        "chunk_seconds": chunk_seconds,
        "total_bytes": total_bytes,
        "covers_seconds": covers_seconds,
        "oldest_ts": oldest_ts or 0,
        "newest_ts": newest_ts or 0,
    }


cfg_boot = load_config()
app.secret_key = cfg_boot.get("secret_key", secrets.token_hex(32))


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

PIN_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>RadioResurrector</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    background: #0f0f1a;
    color: #e0e0f0;
    font-family: system-ui, sans-serif;
    min-height: 100dvh;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .card {
    background: #1a1a2e;
    border: 1px solid #2a2a4a;
    border-radius: 16px;
    padding: 2.5rem 2rem;
    width: 100%;
    max-width: 360px;
    text-align: center;
    box-shadow: 0 8px 32px rgba(0,0,0,.5);
  }
  .logo { font-size: 2.8rem; margin-bottom: .5rem; }
  h1 { font-size: 1.3rem; font-weight: 700; color: #a78bfa; margin-bottom: .25rem; }
  .sub { font-size: .85rem; color: #666; margin-bottom: 2rem; }
  input[type=password] {
    background: #0f0f1a;
    border: 1px solid #2a2a4a;
    border-radius: 10px;
    color: #e0e0f0;
    font-size: 1.6rem;
    letter-spacing: .5rem;
    padding: .75rem 1rem;
    text-align: center;
    width: 100%;
    margin-bottom: 1.25rem;
    outline: none;
    transition: border-color .2s;
  }
  input:focus { border-color: #a78bfa; }
  button {
    background: #7c3aed;
    border: none;
    border-radius: 10px;
    color: #fff;
    cursor: pointer;
    font-size: 1rem;
    font-weight: 600;
    padding: .8rem 2rem;
    width: 100%;
    transition: background .2s;
  }
  button:hover { background: #6d28d9; }
  .error { color: #f87171; font-size: .9rem; margin-bottom: 1rem; }
</style>
</head>
<body>
<div class="card">
  <div class="logo">📻</div>
  <h1>RadioResurrector</h1>
  <p class="sub">Enter your PIN to continue</p>
  {% if error %}<p class="error">{{ error }}</p>{% endif %}
  <form method="post">
    <input type="password" name="pin" inputmode="numeric" pattern="[0-9]*"
           maxlength="8" autofocus placeholder="••••">
    <button type="submit">Unlock</button>
  </form>
</div>
</body>
</html>"""


MAIN_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>RadioResurrector</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  :root {
    --bg: #0f0f1a;
    --card: #1a1a2e;
    --border: #2a2a4a;
    --accent: #7c3aed;
    --accent-light: #a78bfa;
    --text: #e0e0f0;
    --muted: #666;
    --green: #34d399;
    --red: #f87171;
    --yellow: #fbbf24;
    --orange: #fb923c;
  }
  body {
    background: var(--bg);
    color: var(--text);
    font-family: system-ui, sans-serif;
    padding: 1rem;
    padding-bottom: 5rem;
    max-width: 600px;
    margin: 0 auto;
  }

  header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 1.25rem;
  }
  .logo-group { display: flex; align-items: center; gap: .6rem; }
  .logo-group span:first-child { font-size: 1.6rem; }
  .logo-group h1 { font-size: 1.1rem; color: var(--accent-light); font-weight: 700; }
  .logout {
    background: none; border: 1px solid var(--border);
    border-radius: 8px; color: var(--muted);
    cursor: pointer; font-size: .8rem; padding: .4rem .8rem;
  }
  .logout:hover { border-color: var(--muted); color: var(--text); }

  /* ── Now Playing ── */
  .now-playing {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 14px;
    padding: 1.25rem;
    margin-bottom: 1rem;
    position: relative;
    overflow: hidden;
  }
  .now-playing::before {
    content: '';
    position: absolute;
    inset: 0;
    opacity: .06;
    pointer-events: none;
    background: var(--np-color, transparent);
  }
  .np-header {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 1rem;
    margin-bottom: .9rem;
  }
  .np-badge {
    display: inline-flex;
    align-items: center;
    gap: .4rem;
    border-radius: 999px;
    font-size: .75rem;
    font-weight: 800;
    letter-spacing: .08em;
    padding: .3rem .75rem;
    text-transform: uppercase;
    flex-shrink: 0;
  }
  .np-badge.live    { background: rgba(52,211,153,.15); color: var(--green);  border: 1px solid rgba(52,211,153,.3); }
  .np-badge.buffer  { background: rgba(251,191,36,.12); color: var(--yellow); border: 1px solid rgba(251,191,36,.3); }
  .np-badge.starting{ background: rgba(251,146,60,.12); color: var(--orange); border: 1px solid rgba(251,146,60,.3); }
  .np-badge.unknown, .np-badge.stopped {
    background: rgba(248,113,113,.12); color: var(--red); border: 1px solid rgba(248,113,113,.3);
  }
  .pulse {
    width: 8px; height: 8px;
    border-radius: 50%;
    background: currentColor;
    animation: pulse 1.8s ease-in-out infinite;
  }
  .np-badge.live .pulse { animation: pulse 1.8s ease-in-out infinite; }
  .np-badge:not(.live) .pulse { animation: none; }
  @keyframes pulse {
    0%, 100% { opacity: 1; transform: scale(1); }
    50%       { opacity: .4; transform: scale(.7); }
  }
  .np-duration {
    font-size: .8rem;
    color: var(--muted);
    flex-shrink: 0;
    margin-top: .15rem;
  }
  .np-url {
    font-size: .82rem;
    color: var(--muted);
    word-break: break-all;
    line-height: 1.5;
    border-top: 1px solid var(--border);
    padding-top: .75rem;
  }
  .np-url strong { color: var(--text); font-weight: 600; display: block; margin-bottom: .2rem; }

  /* Service dot */
  .svc-row {
    display: flex;
    align-items: center;
    gap: .5rem;
  }
  .dot {
    width: 8px; height: 8px;
    border-radius: 50%;
    background: var(--muted);
    flex-shrink: 0;
  }
  .dot.active   { background: var(--green); box-shadow: 0 0 5px var(--green); }
  .dot.inactive, .dot.failed { background: var(--red); }
  .dot.activating { background: var(--yellow); }
  .svc-label { font-size: .78rem; color: var(--muted); }

  /* ── Buffer monitor ── */
  .card {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 14px;
    padding: 1.25rem;
    margin-bottom: 1rem;
  }
  .card-title {
    font-size: .7rem;
    font-weight: 700;
    letter-spacing: .1em;
    text-transform: uppercase;
    color: var(--muted);
    margin-bottom: 1rem;
  }

  .buf-stats {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: .5rem;
    margin-bottom: 1rem;
  }
  .buf-stat {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: .65rem .5rem;
    text-align: center;
  }
  .buf-stat-val {
    font-size: 1.15rem;
    font-weight: 700;
    color: var(--accent-light);
    display: block;
  }
  .buf-stat-lbl {
    font-size: .7rem;
    color: var(--muted);
    display: block;
    margin-top: .1rem;
  }

  /* Fill bar */
  .fill-bar-wrap {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 999px;
    height: 10px;
    overflow: hidden;
    margin-bottom: .4rem;
  }
  .fill-bar-inner {
    height: 100%;
    border-radius: 999px;
    background: linear-gradient(90deg, var(--accent), var(--accent-light));
    transition: width .6s ease;
    min-width: 4px;
  }
  .fill-bar-label {
    display: flex;
    justify-content: space-between;
    font-size: .72rem;
    color: var(--muted);
    margin-bottom: 1rem;
  }

  /* Chunk list */
  .chunk-list-wrap {
    max-height: 200px;
    overflow-y: auto;
    border: 1px solid var(--border);
    border-radius: 10px;
    margin-bottom: 1rem;
    scrollbar-width: thin;
    scrollbar-color: var(--border) transparent;
  }
  .chunk-list {
    width: 100%;
    border-collapse: collapse;
    font-size: .78rem;
  }
  .chunk-list thead th {
    background: var(--bg);
    color: var(--muted);
    font-weight: 600;
    padding: .45rem .75rem;
    text-align: left;
    position: sticky;
    top: 0;
    letter-spacing: .04em;
    font-size: .7rem;
    text-transform: uppercase;
  }
  .chunk-list tbody tr { border-top: 1px solid var(--border); }
  .chunk-list tbody tr:hover { background: rgba(167,139,250,.05); }
  .chunk-list td { padding: .4rem .75rem; color: var(--text); }
  .chunk-list td.dim { color: var(--muted); }
  .chunk-list td.right { text-align: right; }

  /* Buttons */
  .btn {
    border: none;
    border-radius: 10px;
    cursor: pointer;
    font-size: .9rem;
    font-weight: 600;
    padding: .7rem 1.2rem;
    transition: opacity .2s, background .2s;
  }
  .btn:disabled { opacity: .4; cursor: not-allowed; }
  .btn-primary { background: var(--accent); color: #fff; }
  .btn-primary:hover:not(:disabled) { background: #6d28d9; }
  .btn-danger { background: #7f1d1d; color: #fca5a5; }
  .btn-danger:hover:not(:disabled) { background: #991b1b; }
  .btn-success { background: #064e3b; color: #6ee7b7; }
  .btn-success:hover:not(:disabled) { background: #065f46; }
  .btn-sm { font-size: .8rem; padding: .4rem .9rem; border-radius: 8px; }
  .btn-ghost {
    background: none; border: 1px solid var(--border);
    color: var(--muted);
  }
  .btn-ghost:hover:not(:disabled) { border-color: var(--accent-light); color: var(--text); }
  .btn-row { display: flex; gap: .6rem; flex-wrap: wrap; }
  .btn-row .btn { flex: 1; }

  /* Stream */
  .stream-row { display: flex; gap: .6rem; margin-bottom: .75rem; }
  .stream-row select, .stream-row input {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 8px;
    color: var(--text);
    font-size: .9rem;
    padding: .55rem .75rem;
    outline: none;
    transition: border-color .2s;
  }
  .stream-row select { flex: 0 0 auto; }
  .stream-row input { flex: 1; min-width: 0; }
  input:focus, select:focus { border-color: var(--accent-light); }

  /* Sliders */
  .slider-row { margin-bottom: 1rem; }
  .slider-row:last-child { margin-bottom: 0; }
  .slider-header {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    margin-bottom: .4rem;
  }
  .slider-label { font-size: .9rem; }
  .slider-value {
    font-size: .9rem; font-weight: 700;
    color: var(--accent-light); min-width: 4rem; text-align: right;
  }
  input[type=range] {
    -webkit-appearance: none; appearance: none;
    width: 100%; height: 6px;
    background: var(--border); border-radius: 3px;
    outline: none; cursor: pointer;
  }
  input[type=range]::-webkit-slider-thumb {
    -webkit-appearance: none;
    width: 20px; height: 20px;
    border-radius: 50%; background: var(--accent);
    cursor: pointer; transition: background .15s;
  }
  input[type=range]::-webkit-slider-thumb:hover { background: var(--accent-light); }

  /* Presets */
  .preset-list { list-style: none; }
  .preset-item {
    display: flex; align-items: center; gap: .6rem;
    padding: .5rem 0; border-bottom: 1px solid var(--border);
  }
  .preset-item:last-child { border-bottom: none; }
  .preset-name { flex: 0 0 120px; font-size: .85rem; font-weight: 600; }
  .preset-url { flex: 1; font-size: .75rem; color: var(--muted); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .add-preset-row { display: flex; gap: .5rem; margin-top: .75rem; flex-wrap: wrap; }
  .add-preset-row input {
    background: var(--bg); border: 1px solid var(--border);
    border-radius: 8px; color: var(--text); font-size: .85rem;
    padding: .45rem .7rem; outline: none; flex: 1; min-width: 80px;
  }
  .add-preset-row input:focus { border-color: var(--accent-light); }

  /* PIN */
  .pin-row { display: flex; gap: .6rem; }
  .pin-row input {
    background: var(--bg); border: 1px solid var(--border);
    border-radius: 8px; color: var(--text); font-size: 1rem;
    letter-spacing: .2rem; padding: .55rem .75rem;
    text-align: center; width: 100px; outline: none; flex-shrink: 0;
  }
  .pin-row input:focus { border-color: var(--accent-light); }

  /* Toast */
  #toast {
    position: fixed; bottom: 1.5rem; left: 50%;
    transform: translateX(-50%);
    background: #1e1b4b; border: 1px solid var(--accent);
    border-radius: 10px; color: var(--text);
    font-size: .9rem; padding: .7rem 1.5rem;
    opacity: 0; pointer-events: none; transition: opacity .3s;
    white-space: nowrap; z-index: 100;
  }
  #toast.show { opacity: 1; }
  #toast.error { border-color: var(--red); background: #2d1515; }

  /* Confirm dialog */
  .overlay {
    display: none; position: fixed; inset: 0;
    background: rgba(0,0,0,.7); z-index: 200;
    align-items: center; justify-content: center;
  }
  .overlay.open { display: flex; }
  .dialog {
    background: var(--card); border: 1px solid var(--border);
    border-radius: 16px; padding: 1.75rem 1.5rem;
    max-width: 320px; width: 90%; text-align: center;
  }
  .dialog h2 { font-size: 1rem; margin-bottom: .5rem; }
  .dialog p { font-size: .85rem; color: var(--muted); margin-bottom: 1.25rem; }
  .dialog .btn-row { justify-content: center; }
  .dialog .btn { flex: 0 1 auto; min-width: 100px; }
</style>
</head>
<body>

<header>
  <div class="logo-group">
    <span>📻</span>
    <h1>RadioResurrector</h1>
  </div>
  <form action="/logout" method="post">
    <button class="logout" type="submit">Logout</button>
  </form>
</header>

<!-- ── Now Playing ── -->
<div class="now-playing" id="nowPlaying">
  <div class="np-header">
    <span class="np-badge {{ state.mode }}" id="npBadge">
      <span class="pulse"></span>
      <span id="npMode">{{ state.mode | upper }}</span>
    </span>
    <span class="np-duration" id="npDuration">—</span>
  </div>
  <div class="svc-row" style="margin-bottom:.75rem">
    <div class="dot {{ svc_status }}" id="svcDot"></div>
    <span class="svc-label" id="svcLabel">radio.service — {{ svc_status }}</span>
  </div>
  <div class="np-url">
    <strong>Stream</strong>
    <span id="npUrl">{{ state.url or '—' }}</span>
  </div>
</div>

<!-- ── Buffer Monitor ── -->
<div class="card">
  <div class="card-title">📼 Buffer</div>

  <div class="buf-stats">
    <div class="buf-stat">
      <span class="buf-stat-val" id="bChunks">{{ buf.chunk_count }}</span>
      <span class="buf-stat-lbl">chunks</span>
    </div>
    <div class="buf-stat">
      <span class="buf-stat-val" id="bCovers">{{ (buf.covers_seconds // 60) }}m</span>
      <span class="buf-stat-lbl">covered</span>
    </div>
    <div class="buf-stat">
      <span class="buf-stat-val" id="bSize">{{ '%.1f' % (buf.total_bytes / 1048576) }}MB</span>
      <span class="buf-stat-lbl">on disk</span>
    </div>
  </div>

  <div class="fill-bar-wrap">
    <div class="fill-bar-inner" id="fillBar"
         style="width:{{ [100, buf.chunk_count * 100 // [buf.max_chunks,1]|max]|min }}%"></div>
  </div>
  <div class="fill-bar-label">
    <span id="fillLabel">{{ buf.chunk_count }} / {{ buf.max_chunks }} chunks</span>
    <span id="fillPct">{{ [100, buf.chunk_count * 100 // [buf.max_chunks,1]|max]|min }}%</span>
  </div>

  <div class="chunk-list-wrap">
    <table class="chunk-list">
      <thead>
        <tr>
          <th>File</th>
          <th>Size</th>
          <th>Age</th>
        </tr>
      </thead>
      <tbody id="chunkTable">
        {% for f in buf.files | reverse %}
        <tr>
          <td>{{ f.name }}</td>
          <td class="dim">{{ '%.1f' % (f.size / 1048576) }} MB</td>
          <td class="dim right" data-ts="{{ f.mtime }}">—</td>
        </tr>
        {% else %}
        <tr><td colspan="3" class="dim" style="text-align:center;padding:1rem">No buffer files</td></tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <button class="btn btn-danger btn-sm" onclick="confirmClear()">Clear Buffer</button>
</div>

<!-- ── Volume ── -->
<div class="card">
  <div class="card-title">🔊 Volume</div>
  <div class="slider-row">
    <div class="slider-header">
      <span class="slider-label">Output Level</span>
      <span class="slider-value" id="volDisplay">{{ cfg.volume }}%</span>
    </div>
    <input type="range" id="volumeSlider" min="0" max="100"
           value="{{ cfg.volume }}" step="1">
  </div>
</div>

<!-- ── Stream ── -->
<div class="card">
  <div class="card-title">📡 Stream</div>
  <div class="stream-row">
    <select id="presetSelect" onchange="applyPreset()">
      <option value="">— Preset —</option>
      {% for s in cfg.streams %}
      <option value="{{ s.url }}">{{ s.name }}</option>
      {% endfor %}
    </select>
    <input type="text" id="streamUrl" value="{{ cfg.stream_url }}"
           placeholder="https://stream.example.com/live">
  </div>
</div>

<!-- ── Recording Settings ── -->
<div class="card">
  <div class="card-title">⏺ Recording Settings</div>
  <div class="slider-row">
    <div class="slider-header">
      <span class="slider-label">Chunk Size</span>
      <span class="slider-value" id="chunkDisplay">{{ cfg.chunk_seconds }}s</span>
    </div>
    <input type="range" id="chunkSlider" min="60" max="600"
           value="{{ cfg.chunk_seconds }}" step="30"
           oninput="document.getElementById('chunkDisplay').textContent=this.value+'s'">
  </div>
  <div class="slider-row">
    <div class="slider-header">
      <span class="slider-label">Buffer Duration</span>
      <span class="slider-value" id="bufferDisplay">{{ cfg.buffer_minutes }}m</span>
    </div>
    <input type="range" id="bufferSlider" min="30" max="360"
           value="{{ cfg.buffer_minutes }}" step="30"
           oninput="document.getElementById('bufferDisplay').textContent=this.value+'m'">
  </div>
  <div class="slider-row">
    <div class="slider-header">
      <span class="slider-label">Check Interval</span>
      <span class="slider-value" id="intervalDisplay">{{ cfg.check_interval }}s</span>
    </div>
    <input type="range" id="intervalSlider" min="5" max="60"
           value="{{ cfg.check_interval }}" step="5"
           oninput="document.getElementById('intervalDisplay').textContent=this.value+'s'">
  </div>
</div>

<!-- ── Apply ── -->
<div class="card">
  <div class="card-title">Apply Changes</div>
  <p style="font-size:.85rem;color:var(--muted);margin-bottom:1rem;">
    Saves all settings and restarts the radio service.
  </p>
  <button class="btn btn-primary" style="width:100%" onclick="applySettings()">
    Apply &amp; Restart
  </button>
</div>

<!-- ── Service Controls ── -->
<div class="card">
  <div class="card-title">⚙ Service</div>
  <div class="btn-row">
    <button class="btn btn-success" onclick="serviceAction('start')">Start</button>
    <button class="btn btn-ghost" onclick="serviceAction('restart')">Restart</button>
    <button class="btn btn-danger" onclick="serviceAction('stop')">Stop</button>
  </div>
</div>

<!-- ── Stream Presets ── -->
<div class="card">
  <div class="card-title">📋 Stream Presets</div>
  <ul class="preset-list" id="presetList">
    {% for s in cfg.streams %}
    <li class="preset-item" data-url="{{ s.url }}">
      <span class="preset-name">{{ s.name }}</span>
      <span class="preset-url">{{ s.url }}</span>
      <button class="btn btn-sm btn-danger"
              onclick="removePreset('{{ s.url }}')">✕</button>
    </li>
    {% endfor %}
  </ul>
  <div class="add-preset-row">
    <input type="text" id="newPresetName" placeholder="Name">
    <input type="text" id="newPresetUrl" placeholder="Stream URL">
    <button class="btn btn-sm btn-primary" onclick="addPreset()">Add</button>
  </div>
</div>

<!-- ── Change PIN ── -->
<div class="card">
  <div class="card-title">🔒 Change PIN</div>
  <div class="pin-row">
    <input type="password" id="newPin" inputmode="numeric"
           pattern="[0-9]*" maxlength="8" placeholder="New PIN">
    <button class="btn btn-primary btn-sm" onclick="changePin()">Save PIN</button>
  </div>
</div>

<!-- Clear Buffer confirmation -->
<div class="overlay" id="clearOverlay">
  <div class="dialog">
    <h2>Clear buffer?</h2>
    <p>This deletes all cached audio files. If the live stream is down, playback will stop until new chunks are recorded.</p>
    <div class="btn-row">
      <button class="btn btn-ghost" onclick="closeClear()">Cancel</button>
      <button class="btn btn-danger" onclick="doClear()">Clear</button>
    </div>
  </div>
</div>

<div id="toast"></div>

<script>
// ── Toast ──
function toast(msg, isError=false) {
  const t = document.getElementById('toast');
  t.textContent = msg;
  t.className = 'show' + (isError ? ' error' : '');
  clearTimeout(window._toastTimer);
  window._toastTimer = setTimeout(() => t.className = '', 2500);
}

// ── Relative time ──
function relTime(ts) {
  const s = Math.floor(Date.now() / 1000) - ts;
  if (s < 60)  return s + 's ago';
  if (s < 3600) return Math.floor(s/60) + 'm ago';
  return Math.floor(s/3600) + 'h ago';
}

function durSince(ts) {
  if (!ts) return '—';
  const s = Math.floor(Date.now() / 1000) - ts;
  if (s < 0) return '—';
  if (s < 60) return s + 's';
  if (s < 3600) return Math.floor(s/60) + 'm ' + (s%60) + 's';
  return Math.floor(s/3600) + 'h ' + Math.floor((s%3600)/60) + 'm';
}

function fmtMB(bytes) {
  return (bytes/1048576).toFixed(1) + 'MB';
}

// ── Age cells ──
function refreshAgeCells() {
  document.querySelectorAll('[data-ts]').forEach(td => {
    td.textContent = relTime(parseInt(td.dataset.ts));
  });
}
setInterval(refreshAgeCells, 10000);
refreshAgeCells();

// ── Now Playing duration ticker ──
let npSince = {{ state.since or 0 }};
function tickDuration() {
  document.getElementById('npDuration').textContent = durSince(npSince);
}
setInterval(tickDuration, 1000);
tickDuration();

// ── Preset select ──
function applyPreset() {
  const sel = document.getElementById('presetSelect');
  if (sel.value) document.getElementById('streamUrl').value = sel.value;
  sel.value = '';
}

// ── Volume (debounced live update) ──
const volSlider = document.getElementById('volumeSlider');
const volDisplay = document.getElementById('volDisplay');
let volTimer;
volSlider.addEventListener('input', () => {
  volDisplay.textContent = volSlider.value + '%';
  clearTimeout(volTimer);
  volTimer = setTimeout(() => {
    api('/volume', { volume: parseInt(volSlider.value) })
      .then(() => toast('Volume → ' + volSlider.value + '%'))
      .catch(() => toast('Volume update failed', true));
  }, 400);
});

// ── Apply settings ──
function applySettings() {
  const payload = {
    stream_url:     document.getElementById('streamUrl').value.trim(),
    chunk_seconds:  parseInt(document.getElementById('chunkSlider').value),
    buffer_minutes: parseInt(document.getElementById('bufferSlider').value),
    check_interval: parseInt(document.getElementById('intervalSlider').value),
    volume:         parseInt(volSlider.value),
  };
  if (!payload.stream_url) return toast('Stream URL is required', true);
  api('/apply', payload)
    .then(() => toast('Settings saved — restarting service'))
    .catch(() => toast('Failed to apply settings', true));
}

// ── Service actions ──
function serviceAction(action) {
  api('/service/' + action, {})
    .then(d => { toast('Service ' + action + 'ed'); updateSvc(d.status); })
    .catch(() => toast('Service action failed', true));
}

// ── Update Now Playing UI ──
function updateNP(state) {
  const badge = document.getElementById('npBadge');
  const modeEl = document.getElementById('npMode');
  const urlEl  = document.getElementById('npUrl');
  badge.className = 'np-badge ' + state.mode;
  modeEl.textContent = state.mode.toUpperCase();
  urlEl.textContent  = state.url || '—';
  npSince = state.since || 0;
}

function updateSvc(status) {
  const dot   = document.getElementById('svcDot');
  const label = document.getElementById('svcLabel');
  dot.className  = 'dot ' + status;
  label.textContent = 'radio.service — ' + status;
}

// ── Update buffer UI ──
function updateBuffer(buf) {
  document.getElementById('bChunks').textContent  = buf.chunk_count;
  document.getElementById('bCovers').textContent  = Math.floor(buf.covers_seconds / 60) + 'm';
  document.getElementById('bSize').textContent    = fmtMB(buf.total_bytes);

  const pct = buf.max_chunks ? Math.min(100, Math.round(buf.chunk_count * 100 / buf.max_chunks)) : 0;
  document.getElementById('fillBar').style.width  = pct + '%';
  document.getElementById('fillLabel').textContent = buf.chunk_count + ' / ' + buf.max_chunks + ' chunks';
  document.getElementById('fillPct').textContent   = pct + '%';

  // Rebuild chunk table
  const tbody = document.getElementById('chunkTable');
  if (!buf.files.length) {
    tbody.innerHTML = '<tr><td colspan="3" class="dim" style="text-align:center;padding:1rem">No buffer files</td></tr>';
    return;
  }
  tbody.innerHTML = [...buf.files].reverse().map(f =>
    `<tr>
      <td>${esc(f.name)}</td>
      <td class="dim">${(f.size/1048576).toFixed(1)} MB</td>
      <td class="dim right" data-ts="${f.mtime}">${relTime(f.mtime)}</td>
    </tr>`
  ).join('');
}

// ── Poll status + buffer every 8 s ──
function poll() {
  fetch('/status')
    .then(r => r.json())
    .then(d => {
      updateNP(d.state);
      updateSvc(d.svc_status);
      updateBuffer(d.buffer);
    })
    .catch(() => {});
}
setInterval(poll, 8000);

// ── Clear buffer ──
function confirmClear() { document.getElementById('clearOverlay').classList.add('open'); }
function closeClear()   { document.getElementById('clearOverlay').classList.remove('open'); }
function doClear() {
  closeClear();
  api('/buffer/clear', {})
    .then(d => { toast('Buffer cleared'); updateBuffer(d.buffer); })
    .catch(() => toast('Failed to clear buffer', true));
}

// ── Presets ──
function addPreset() {
  const name = document.getElementById('newPresetName').value.trim();
  const url  = document.getElementById('newPresetUrl').value.trim();
  if (!name || !url) return toast('Name and URL are required', true);
  api('/presets/add', { name, url })
    .then(() => {
      toast('Preset added');
      document.getElementById('newPresetName').value = '';
      document.getElementById('newPresetUrl').value  = '';
      addPresetToDOM(name, url);
      addPresetToSelect(name, url);
    })
    .catch(() => toast('Failed to add preset', true));
}

function removePreset(url) {
  api('/presets/remove', { url })
    .then(() => {
      toast('Preset removed');
      const item = document.querySelector(`[data-url="${CSS.escape(url)}"]`);
      if (item) item.remove();
      const opt = document.querySelector(`#presetSelect option[value="${CSS.escape(url)}"]`);
      if (opt) opt.remove();
    })
    .catch(() => toast('Failed to remove preset', true));
}

function addPresetToDOM(name, url) {
  const li = document.createElement('li');
  li.className = 'preset-item'; li.dataset.url = url;
  li.innerHTML = `<span class="preset-name">${esc(name)}</span>
    <span class="preset-url">${esc(url)}</span>
    <button class="btn btn-sm btn-danger" onclick="removePreset('${esc(url)}')">✕</button>`;
  document.getElementById('presetList').appendChild(li);
}
function addPresetToSelect(name, url) {
  const opt = document.createElement('option');
  opt.value = url; opt.textContent = name;
  document.getElementById('presetSelect').appendChild(opt);
}

// ── PIN ──
function changePin() {
  const pin = document.getElementById('newPin').value.trim();
  if (!/^\d{4,8}$/.test(pin)) return toast('PIN must be 4–8 digits', true);
  api('/pin', { pin })
    .then(() => { toast('PIN updated'); document.getElementById('newPin').value = ''; })
    .catch(() => toast('Failed to update PIN', true));
}

// ── Escape helper ──
function esc(s) {
  return String(s)
    .replace(/&/g,'&amp;').replace(/</g,'&lt;')
    .replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

// ── API helper ──
function api(path, body) {
  return fetch(path, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  }).then(r => { if (!r.ok) throw new Error(r.status); return r.json(); });
}
</script>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

def require_auth():
    return session.get("authed") is True


@app.route("/", methods=["GET", "POST"])
def index():
    if require_auth():
        return redirect(url_for("dashboard"))
    if request.method == "POST":
        cfg = load_config()
        if request.form.get("pin") == cfg["pin"]:
            session["authed"] = True
            return redirect(url_for("dashboard"))
        return render_template_string(PIN_PAGE, error="Incorrect PIN — try again")
    return render_template_string(PIN_PAGE, error=None)


@app.route("/dashboard")
def dashboard():
    if not require_auth():
        return redirect(url_for("index"))
    cfg = load_config()
    return render_template_string(
        MAIN_PAGE,
        cfg=cfg,
        state=playback_state(),
        svc_status=service_status(),
        buf=buffer_info(),
    )


@app.route("/logout", methods=["POST"])
def logout():
    session.clear()
    return redirect(url_for("index"))


@app.route("/status")
def get_status():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    return jsonify({
        "svc_status": service_status(),
        "state": playback_state(),
        "buffer": buffer_info(),
    })


@app.route("/apply", methods=["POST"])
def apply():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    data = request.get_json(force=True)
    cfg = load_config()
    cfg["stream_url"]     = str(data.get("stream_url", cfg["stream_url"]))
    cfg["chunk_seconds"]  = max(60, min(600, int(data.get("chunk_seconds", cfg["chunk_seconds"]))))
    cfg["buffer_minutes"] = max(30, min(360, int(data.get("buffer_minutes", cfg["buffer_minutes"]))))
    cfg["check_interval"] = max(5, min(60, int(data.get("check_interval", cfg["check_interval"]))))
    cfg["volume"]         = max(0, min(100, int(data.get("volume", cfg["volume"]))))
    save_config(cfg)
    subprocess.run(["systemctl", "restart", "radio.service"], timeout=10)
    return jsonify({"ok": True})


@app.route("/volume", methods=["POST"])
def set_volume():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    vol = max(0, min(100, int(request.get_json(force=True).get("volume", 90))))
    subprocess.run(["amixer", "sset", "PCM", f"{vol}%"], capture_output=True)
    cfg = load_config()
    cfg["volume"] = vol
    save_config(cfg)
    return jsonify({"ok": True, "volume": vol})


@app.route("/service/<action>", methods=["POST"])
def service_action(action):
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    if action not in ("start", "stop", "restart"):
        return jsonify({"error": "invalid action"}), 400
    subprocess.run(["systemctl", action, "radio.service"], timeout=10)
    return jsonify({"ok": True, "status": service_status()})


@app.route("/buffer/clear", methods=["POST"])
def clear_buffer():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    try:
        for name in os.listdir(BUFFER_DIR):
            if name.endswith(".mp3") or name.endswith(".m3u"):
                os.remove(os.path.join(BUFFER_DIR, name))
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True, "buffer": buffer_info()})


@app.route("/presets/add", methods=["POST"])
def add_preset():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    data = request.get_json(force=True)
    name = str(data.get("name", "")).strip()[:64]
    url  = str(data.get("url",  "")).strip()[:512]
    if not name or not url:
        return jsonify({"error": "name and url required"}), 400
    cfg = load_config()
    cfg["streams"] = [s for s in cfg.get("streams", []) if s["url"] != url]
    cfg["streams"].append({"name": name, "url": url})
    save_config(cfg)
    return jsonify({"ok": True})


@app.route("/presets/remove", methods=["POST"])
def remove_preset():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    url = str(request.get_json(force=True).get("url", "")).strip()
    cfg = load_config()
    cfg["streams"] = [s for s in cfg.get("streams", []) if s["url"] != url]
    save_config(cfg)
    return jsonify({"ok": True})


@app.route("/pin", methods=["POST"])
def change_pin():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    pin = str(request.get_json(force=True).get("pin", "")).strip()
    if not pin.isdigit() or not (4 <= len(pin) <= 8):
        return jsonify({"error": "PIN must be 4–8 digits"}), 400
    cfg = load_config()
    cfg["pin"] = pin
    save_config(cfg)
    return jsonify({"ok": True})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080, debug=False)
