#!/usr/bin/env python3
"""RadioResurrector Web Interface"""

import json
import os
import secrets
import subprocess
import threading
import time
import urllib.request
import urllib.parse
import xml.etree.ElementTree as ET
from urllib.parse import urlparse

from flask import Flask, Response, jsonify, redirect, render_template_string, request, session, url_for

# Set RADIO_DIR env var to run locally, e.g.:
#   RADIO_DIR=/tmp/radio python3 web.py
BASE_DIR         = os.environ.get("RADIO_DIR", "/opt/radio")
CONFIG_FILE      = os.path.join(BASE_DIR, "config.json")
CONFIG_SH        = os.path.join(BASE_DIR, "config.sh")
BUFFER_DIR       = os.path.join(BASE_DIR, "buffer")
STATE_FILE       = os.path.join(BASE_DIR, "state.json")
FORCE_BUFFER     = os.path.join(BASE_DIR, "force_buffer")

os.makedirs(BUFFER_DIR, exist_ok=True)  # ensure dirs exist in dev too

app = Flask(__name__)

DEFAULT_CONFIG = {
    "secret_key": secrets.token_hex(32),
    "pin": "1234",
    "stream_url": "https://findyourownstream.example/stream",
    "chunk_seconds": 300,
    "buffer_minutes": 120,
    "check_interval": 10,
    "volume": 90,
    "streams": [
        {"name": "Example Stream", "url": "https://findyourownstream.example/stream"}
    ],
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_config():
    if not os.path.exists(CONFIG_FILE):
        save_config(DEFAULT_CONFIG)
        return DEFAULT_CONFIG
    with open(CONFIG_FILE) as f:
        return json.load(f)


def save_config(cfg):
    with open(CONFIG_FILE, "w") as f:
        json.dump(cfg, f, indent=2)
    write_shell_config(cfg)


def write_shell_config(cfg):
    with open(CONFIG_SH, "w") as f:
        f.write("# Auto-generated by RadioResurrector web interface — do not edit manually\n")
        f.write(f'STREAM_URL="{cfg["stream_url"]}"\n')
        f.write(f'CHUNK_SECONDS={cfg["chunk_seconds"]}\n')
        f.write(f'BUFFER_MINUTES={cfg["buffer_minutes"]}\n')
        f.write(f'MAX_CHUNKS=$(( BUFFER_MINUTES * 60 / CHUNK_SECONDS ))\n')
        f.write(f'CHECK_INTERVAL={cfg["check_interval"]}\n')
        f.write(f'VOLUME={cfg["volume"]}\n')


def service_status():
    try:
        r = subprocess.run(
            ["systemctl", "is-active", "radio.service"],
            capture_output=True, text=True, timeout=5,
        )
        return r.stdout.strip()
    except Exception:
        return "unknown"


def playback_state():
    """Read state.json written by radio.sh and enrich with stream name."""
    try:
        with open(STATE_FILE) as f:
            state = json.load(f)
    except Exception:
        state = {"mode": "unknown", "url": "", "since": 0}

    url = state.get("url", "")
    cfg = load_config()

    # Resolve stream name from presets
    name = None
    for s in cfg.get("streams", []):
        if s["url"] == url:
            name = s["name"]
            break
    if name is None:
        try:
            name = urlparse(url).hostname or url
        except Exception:
            name = url

    state["name"] = name
    state["forced"] = os.path.exists(FORCE_BUFFER)
    return state


def buffer_info():
    cfg = load_config()
    chunk_seconds = cfg.get("chunk_seconds", 300)
    max_chunks    = cfg.get("buffer_minutes", 120) * 60 // chunk_seconds

    try:
        files = sorted(f for f in os.listdir(BUFFER_DIR) if f.endswith(".mp3"))
    except Exception:
        files = []

    file_details = []
    total_bytes  = 0
    oldest_ts    = None
    newest_ts    = None

    for name in files:
        path = os.path.join(BUFFER_DIR, name)
        try:
            st = os.stat(path)
            sz, mt = st.st_size, int(st.st_mtime)
        except OSError:
            continue
        total_bytes += sz
        oldest_ts = mt if oldest_ts is None else min(oldest_ts, mt)
        newest_ts = mt if newest_ts is None else max(newest_ts, mt)
        file_details.append({"name": name, "size": sz, "mtime": mt})

    return {
        "files":          file_details,
        "chunk_count":    len(file_details),
        "max_chunks":     max_chunks,
        "chunk_seconds":  chunk_seconds,
        "total_bytes":    total_bytes,
        "covers_seconds": len(file_details) * chunk_seconds,
        "oldest_ts":      oldest_ts or 0,
        "newest_ts":      newest_ts or 0,
    }


# ---------------------------------------------------------------------------
# Icecast YP directory
# ---------------------------------------------------------------------------

_yp_lock  = threading.Lock()
_yp_cache = {"genres": None, "by_genre": None, "ts": 0}
YP_TTL    = 300  # seconds between refreshes


YP_URLS = [
    "https://dir.xiph.org/yp.php",
    "http://dir.xiph.org/yp.php",
]
YP_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0 Safari/537.36"
    ),
    "Accept": "application/xml, text/xml, */*",
}


def fetch_yp():
    """Download and cache the Icecast YP XML feed, grouped by genre."""
    with _yp_lock:
        if _yp_cache["genres"] and time.time() - _yp_cache["ts"] < YP_TTL:
            return _yp_cache

        last_err = None
        root = None
        for url in YP_URLS:
            try:
                req = urllib.request.Request(url, headers=YP_HEADERS)
                with urllib.request.urlopen(req, timeout=20) as r:
                    root = ET.fromstring(r.read())
                break
            except Exception as e:
                last_err = e
        if root is None:
            raise last_err or RuntimeError("Could not fetch YP feed")

        by_genre: dict = {}
        for e in root.findall("entry"):
            name  = (e.findtext("server_name")   or "").strip()
            url   = (e.findtext("listen_url")     or "").strip()
            genre = (e.findtext("genre")          or "Other").strip() or "Other"
            if not name or not url:
                continue
            entry = {
                "name":    name,
                "url":     url,
                "bitrate": (e.findtext("bitrate")       or "").strip(),
                "song":    (e.findtext("current_song")  or "").strip(),
            }
            by_genre.setdefault(genre, []).append(entry)

        genres = sorted(
            [{"name": g, "count": len(v)} for g, v in by_genre.items()],
            key=lambda x: -x["count"],
        )
        _yp_cache.update({"genres": genres, "by_genre": by_genre, "ts": time.time()})
        return _yp_cache


cfg_boot = load_config()
app.secret_key = cfg_boot.get("secret_key", secrets.token_hex(32))


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

PIN_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>RadioResurrector</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    background: #0f0f1a; color: #e0e0f0;
    font-family: system-ui, sans-serif;
    min-height: 100dvh; display: flex;
    align-items: center; justify-content: center;
  }
  .card {
    background: #1a1a2e; border: 1px solid #2a2a4a;
    border-radius: 16px; padding: 2.5rem 2rem;
    width: 100%; max-width: 360px; text-align: center;
    box-shadow: 0 8px 32px rgba(0,0,0,.5);
  }
  .logo { font-size: 2.8rem; margin-bottom: .5rem; }
  h1 { font-size: 1.3rem; font-weight: 700; color: #a78bfa; margin-bottom: .25rem; }
  .sub { font-size: .85rem; color: #666; margin-bottom: 2rem; }
  input[type=password] {
    background: #0f0f1a; border: 1px solid #2a2a4a; border-radius: 10px;
    color: #e0e0f0; font-size: 1.6rem; letter-spacing: .5rem;
    padding: .75rem 1rem; text-align: center; width: 100%;
    margin-bottom: 1.25rem; outline: none; transition: border-color .2s;
  }
  input:focus { border-color: #a78bfa; }
  button {
    background: #7c3aed; border: none; border-radius: 10px;
    color: #fff; cursor: pointer; font-size: 1rem; font-weight: 600;
    padding: .8rem 2rem; width: 100%; transition: background .2s;
  }
  button:hover { background: #6d28d9; }
  .error { color: #f87171; font-size: .9rem; margin-bottom: 1rem; }
</style>
</head>
<body>
<div class="card">
  <div class="logo">📻</div>
  <h1>RadioResurrector</h1>
  <p class="sub">Enter your PIN to continue</p>
  {% if error %}<p class="error">{{ error }}</p>{% endif %}
  <form method="post">
    <input type="password" name="pin" inputmode="numeric" pattern="[0-9]*"
           maxlength="8" autofocus placeholder="••••">
    <button type="submit">Unlock</button>
  </form>
</div>
</body>
</html>"""


MAIN_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>RadioResurrector</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  :root {
    --bg: #0f0f1a; --card: #1a1a2e; --border: #2a2a4a;
    --accent: #7c3aed; --accent-light: #a78bfa; --text: #e0e0f0;
    --muted: #666; --green: #34d399; --red: #f87171;
    --yellow: #fbbf24; --orange: #fb923c;
  }
  body {
    background: var(--bg); color: var(--text);
    font-family: system-ui, sans-serif;
    padding: 1rem 1.25rem; padding-bottom: 4rem;
    max-width: 1200px; margin: 0 auto;
  }

  /* ── Two-column grid on desktop ── */
  .dashboard-grid {
    display: grid;
    grid-template-columns: 1fr;
    gap: 0;
  }
  @media (min-width: 780px) {
    .dashboard-grid {
      grid-template-columns: minmax(0,1fr) minmax(0,1fr);
      gap: 1.25rem;
      align-items: start;
    }
    .col-right {
      position: sticky;
      top: 1rem;
    }
    .log-body { height: 340px; }
    .chunk-list-wrap { max-height: 220px; }
  }

  /* Header */
  header {
    display: flex; align-items: center;
    justify-content: space-between; margin-bottom: 1.25rem;
  }
  .logo-group { display: flex; align-items: center; gap: .6rem; }
  .logo-group span:first-child { font-size: 1.6rem; }
  .logo-group h1 { font-size: 1.1rem; color: var(--accent-light); font-weight: 700; }
  .logout {
    background: none; border: 1px solid var(--border); border-radius: 8px;
    color: var(--muted); cursor: pointer; font-size: .8rem; padding: .4rem .8rem;
  }
  .logout:hover { border-color: var(--muted); color: var(--text); }

  /* ── Now Playing ── */
  .now-playing {
    background: var(--card); border: 1px solid var(--border);
    border-radius: 14px; padding: 1.25rem; margin-bottom: 1rem;
  }
  .np-top {
    display: flex; align-items: center;
    justify-content: space-between; gap: .75rem; margin-bottom: 1rem;
  }
  .np-badge {
    display: inline-flex; align-items: center; gap: .4rem;
    border-radius: 999px; font-size: .72rem; font-weight: 800;
    letter-spacing: .08em; padding: .28rem .7rem; text-transform: uppercase; flex-shrink: 0;
  }
  .np-badge.live    { background: rgba(52,211,153,.15); color: var(--green);  border: 1px solid rgba(52,211,153,.3); }
  .np-badge.buffer  { background: rgba(251,191,36,.12); color: var(--yellow); border: 1px solid rgba(251,191,36,.3); }
  .np-badge.forced  { background: rgba(251,191,36,.12); color: var(--yellow); border: 1px solid rgba(251,191,36,.3); }
  .np-badge.starting{ background: rgba(251,146,60,.12); color: var(--orange); border: 1px solid rgba(251,146,60,.3); }
  .np-badge.unknown, .np-badge.stopped {
    background: rgba(248,113,113,.12); color: var(--red); border: 1px solid rgba(248,113,113,.3);
  }
  .pulse {
    width: 7px; height: 7px; border-radius: 50%; background: currentColor;
  }
  .np-badge.live .pulse { animation: pulse 1.8s ease-in-out infinite; }
  @keyframes pulse {
    0%,100% { opacity:1; transform:scale(1); }
    50%      { opacity:.35; transform:scale(.65); }
  }
  .np-duration { font-size: .78rem; color: var(--muted); flex-shrink: 0; }

  /* Big title line */
  .np-title {
    font-size: 1.25rem; font-weight: 700; margin-bottom: .3rem;
    white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
  }
  .np-subtitle {
    font-size: .78rem; color: var(--muted);
    word-break: break-all; line-height: 1.5; margin-bottom: 1rem;
  }

  /* Svc row */
  .svc-row { display: flex; align-items: center; gap: .45rem; margin-bottom: 1rem; }
  .dot {
    width: 7px; height: 7px; border-radius: 50%; background: var(--muted); flex-shrink: 0;
  }
  .dot.active   { background: var(--green); box-shadow: 0 0 5px var(--green); }
  .dot.inactive, .dot.failed { background: var(--red); }
  .dot.activating { background: var(--yellow); }
  .svc-label { font-size: .75rem; color: var(--muted); }

  /* Mode switch button */
  .btn-mode {
    width: 100%; border: none; border-radius: 9px; cursor: pointer;
    font-size: .88rem; font-weight: 600; padding: .65rem 1rem;
    transition: background .2s, opacity .2s;
  }
  .btn-mode.to-buffer { background: rgba(251,191,36,.15); color: var(--yellow); border: 1px solid rgba(251,191,36,.3); }
  .btn-mode.to-buffer:hover { background: rgba(251,191,36,.25); }
  .btn-mode.to-live   { background: rgba(52,211,153,.12); color: var(--green);  border: 1px solid rgba(52,211,153,.3); }
  .btn-mode.to-live:hover   { background: rgba(52,211,153,.22); }

  /* ── Log terminal ── */
  .terminal-card {
    background: #080810; border: 1px solid var(--border);
    border-radius: 14px; overflow: hidden; margin-bottom: 1rem;
  }
  .terminal-header {
    background: var(--card); border-bottom: 1px solid var(--border);
    padding: .6rem 1rem; display: flex; align-items: center;
    justify-content: space-between;
  }
  .terminal-title {
    font-size: .7rem; font-weight: 700; letter-spacing: .1em;
    text-transform: uppercase; color: var(--muted);
  }
  .terminal-actions { display: flex; gap: .5rem; }
  .btn-tiny {
    background: none; border: 1px solid var(--border); border-radius: 6px;
    color: var(--muted); cursor: pointer; font-size: .72rem; padding: .2rem .6rem;
  }
  .btn-tiny:hover { border-color: var(--accent-light); color: var(--text); }
  .log-body {
    font-family: 'SF Mono', 'Fira Mono', 'Cascadia Code', monospace;
    font-size: .72rem; line-height: 1.6;
    height: 240px; overflow-y: auto; padding: .75rem;
    scrollbar-width: thin; scrollbar-color: var(--border) transparent;
  }
  .log-line { white-space: pre-wrap; word-break: break-all; }
  .log-ok   { color: #34d399; }
  .log-err  { color: #f87171; }
  .log-warn { color: #fbbf24; }
  .log-info { color: #94a3b8; }
  .log-dim  { color: #3a3a5c; }   /* timestamps / hostname */

  /* ── Cards ── */
  .card {
    background: var(--card); border: 1px solid var(--border);
    border-radius: 14px; padding: 1.25rem; margin-bottom: 1rem;
  }
  .card-title {
    font-size: .7rem; font-weight: 700; letter-spacing: .1em;
    text-transform: uppercase; color: var(--muted); margin-bottom: 1rem;
  }

  /* Buffer stats */
  .buf-stats {
    display: grid; grid-template-columns: repeat(3,1fr);
    gap: .5rem; margin-bottom: 1rem;
  }
  .buf-stat {
    background: var(--bg); border: 1px solid var(--border);
    border-radius: 10px; padding: .65rem .5rem; text-align: center;
  }
  .buf-stat-val { font-size: 1.1rem; font-weight: 700; color: var(--accent-light); display: block; }
  .buf-stat-lbl { font-size: .7rem; color: var(--muted); display: block; margin-top: .1rem; }
  .fill-bar-wrap {
    background: var(--bg); border: 1px solid var(--border);
    border-radius: 999px; height: 9px; overflow: hidden; margin-bottom: .4rem;
  }
  .fill-bar-inner {
    height: 100%; border-radius: 999px;
    background: linear-gradient(90deg, var(--accent), var(--accent-light));
    transition: width .6s ease; min-width: 3px;
  }
  .fill-bar-label {
    display: flex; justify-content: space-between;
    font-size: .72rem; color: var(--muted); margin-bottom: 1rem;
  }
  .chunk-list-wrap {
    max-height: 180px; overflow-y: auto; border: 1px solid var(--border);
    border-radius: 10px; margin-bottom: 1rem;
    scrollbar-width: thin; scrollbar-color: var(--border) transparent;
  }
  .chunk-list { width: 100%; border-collapse: collapse; font-size: .78rem; }
  .chunk-list thead th {
    background: var(--bg); color: var(--muted); font-weight: 600;
    padding: .45rem .75rem; text-align: left; position: sticky; top: 0;
    font-size: .7rem; text-transform: uppercase; letter-spacing: .04em;
  }
  .chunk-list tbody tr { border-top: 1px solid var(--border); }
  .chunk-list tbody tr:hover { background: rgba(167,139,250,.05); }
  .chunk-list td { padding: .38rem .75rem; }
  .chunk-list td.dim { color: var(--muted); }
  .chunk-list td.right { text-align: right; }

  /* Sliders */
  .slider-row { margin-bottom: 1rem; }
  .slider-row:last-child { margin-bottom: 0; }
  .slider-header { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: .4rem; }
  .slider-label { font-size: .9rem; }
  .slider-value { font-size: .9rem; font-weight: 700; color: var(--accent-light); min-width: 4rem; text-align: right; }
  input[type=range] {
    -webkit-appearance: none; appearance: none; width: 100%; height: 6px;
    background: var(--border); border-radius: 3px; outline: none; cursor: pointer;
  }
  input[type=range]::-webkit-slider-thumb {
    -webkit-appearance: none; width: 20px; height: 20px; border-radius: 50%;
    background: var(--accent); cursor: pointer; transition: background .15s;
  }
  input[type=range]::-webkit-slider-thumb:hover { background: var(--accent-light); }

  /* Stream */
  .stream-row { display: flex; gap: .6rem; margin-bottom: .75rem; }
  .stream-row select, .stream-row input {
    background: var(--bg); border: 1px solid var(--border); border-radius: 8px;
    color: var(--text); font-size: .9rem; padding: .55rem .75rem;
    outline: none; transition: border-color .2s;
  }
  .stream-row select { flex: 0 0 auto; }
  .stream-row input { flex: 1; min-width: 0; }
  input:focus, select:focus { border-color: var(--accent-light); }

  /* Buttons */
  .btn {
    border: none; border-radius: 10px; cursor: pointer;
    font-size: .9rem; font-weight: 600; padding: .7rem 1.2rem;
    transition: opacity .2s, background .2s;
  }
  .btn:disabled { opacity: .4; cursor: not-allowed; }
  .btn-primary { background: var(--accent); color: #fff; }
  .btn-primary:hover:not(:disabled) { background: #6d28d9; }
  .btn-danger { background: #7f1d1d; color: #fca5a5; }
  .btn-danger:hover:not(:disabled) { background: #991b1b; }
  .btn-success { background: #064e3b; color: #6ee7b7; }
  .btn-success:hover:not(:disabled) { background: #065f46; }
  .btn-sm { font-size: .8rem; padding: .4rem .9rem; border-radius: 8px; }
  .btn-ghost { background: none; border: 1px solid var(--border); color: var(--muted); }
  .btn-ghost:hover:not(:disabled) { border-color: var(--accent-light); color: var(--text); }
  .btn-row { display: flex; gap: .6rem; flex-wrap: wrap; }
  .btn-row .btn { flex: 1; }

  /* Presets */
  .preset-list { list-style: none; }
  .preset-item { display: flex; align-items: center; gap: .6rem; padding: .5rem 0; border-bottom: 1px solid var(--border); }
  .preset-item:last-child { border-bottom: none; }
  .preset-name { flex: 0 0 120px; font-size: .85rem; font-weight: 600; }
  .preset-url { flex: 1; font-size: .75rem; color: var(--muted); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .add-preset-row { display: flex; gap: .5rem; margin-top: .75rem; flex-wrap: wrap; }
  .add-preset-row input {
    background: var(--bg); border: 1px solid var(--border); border-radius: 8px;
    color: var(--text); font-size: .85rem; padding: .45rem .7rem;
    outline: none; flex: 1; min-width: 80px;
  }
  .add-preset-row input:focus { border-color: var(--accent-light); }

  /* PIN */
  .pin-row { display: flex; gap: .6rem; }
  .pin-row input {
    background: var(--bg); border: 1px solid var(--border); border-radius: 8px;
    color: var(--text); font-size: 1rem; letter-spacing: .2rem;
    padding: .55rem .75rem; text-align: center; width: 100px; outline: none; flex-shrink: 0;
  }
  .pin-row input:focus { border-color: var(--accent-light); }

  /* Toast */
  #toast {
    position: fixed; bottom: 1.5rem; left: 50%; transform: translateX(-50%);
    background: #1e1b4b; border: 1px solid var(--accent); border-radius: 10px;
    color: var(--text); font-size: .9rem; padding: .7rem 1.5rem;
    opacity: 0; pointer-events: none; transition: opacity .3s;
    white-space: nowrap; z-index: 100;
  }
  #toast.show { opacity: 1; }
  #toast.error { border-color: var(--red); background: #2d1515; }

  /* Browse button */
  .btn-browse {
    background: rgba(167,139,250,.12); border: 1px solid rgba(167,139,250,.3);
    border-radius: 8px; color: var(--accent-light); cursor: pointer;
    font-size: .82rem; font-weight: 600; padding: .5rem .9rem;
    white-space: nowrap; flex-shrink: 0; transition: background .2s;
  }
  .btn-browse:hover { background: rgba(167,139,250,.24); }

  /* Confirm dialog */
  .overlay {
    display: none; position: fixed; inset: 0;
    background: rgba(0,0,0,.7); z-index: 200;
    align-items: center; justify-content: center;
  }
  .overlay.open { display: flex; }
  .dialog {
    background: var(--card); border: 1px solid var(--border);
    border-radius: 16px; padding: 1.75rem 1.5rem;
    max-width: 320px; width: 90%; text-align: center;
  }
  .dialog h2 { font-size: 1rem; margin-bottom: .5rem; }
  .dialog p { font-size: .85rem; color: var(--muted); margin-bottom: 1.25rem; }
  .dialog .btn-row { justify-content: center; }
  .dialog .btn { flex: 0 1 auto; min-width: 100px; }

  /* ── Icecast Directory Panel ── */
  .dir-overlay {
    display: none; position: fixed; inset: 0;
    background: rgba(0,0,0,.75); z-index: 300;
    align-items: flex-start; justify-content: center;
    padding: 1rem; overflow-y: auto;
  }
  .dir-overlay.open { display: flex; }
  .dir-panel {
    background: var(--card); border: 1px solid var(--border);
    border-radius: 16px; width: 100%; max-width: 860px;
    margin: auto; display: flex; flex-direction: column;
    max-height: 90dvh;
  }
  .dir-header {
    display: flex; align-items: center; gap: .75rem;
    padding: 1rem 1.25rem; border-bottom: 1px solid var(--border);
    flex-shrink: 0;
  }
  .dir-header h2 { font-size: 1rem; font-weight: 700; flex: 1; }
  .dir-search {
    background: var(--bg); border: 1px solid var(--border); border-radius: 8px;
    color: var(--text); font-size: .88rem; padding: .45rem .75rem;
    outline: none; width: 200px; transition: border-color .2s;
  }
  .dir-search:focus { border-color: var(--accent-light); }
  .dir-close {
    background: none; border: 1px solid var(--border); border-radius: 8px;
    color: var(--muted); cursor: pointer; font-size: .85rem; padding: .35rem .75rem;
  }
  .dir-close:hover { border-color: var(--text); color: var(--text); }
  .dir-breadcrumb {
    display: flex; align-items: center; gap: .5rem;
    padding: .65rem 1.25rem; border-bottom: 1px solid var(--border);
    font-size: .82rem; color: var(--muted); flex-shrink: 0;
    min-height: 2.5rem;
  }
  .dir-crumb-btn {
    background: none; border: none; color: var(--accent-light);
    cursor: pointer; font-size: .82rem; padding: 0; text-decoration: underline;
    text-underline-offset: 2px;
  }
  .dir-body {
    overflow-y: auto; flex: 1;
    scrollbar-width: thin; scrollbar-color: var(--border) transparent;
  }

  /* Genre grid */
  .genre-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(130px, 1fr));
    gap: .6rem; padding: 1rem;
  }
  .genre-tile {
    background: var(--bg); border: 1px solid var(--border); border-radius: 10px;
    cursor: pointer; padding: .75rem .6rem; text-align: center;
    transition: border-color .15s, background .15s;
  }
  .genre-tile:hover { border-color: var(--accent-light); background: rgba(167,139,250,.07); }
  .genre-tile-name { font-size: .85rem; font-weight: 600; margin-bottom: .25rem; word-break: break-word; }
  .genre-tile-count { font-size: .72rem; color: var(--muted); }

  /* Stream list */
  .stream-list { list-style: none; padding: .5rem; }
  .stream-item {
    display: flex; align-items: center; gap: .75rem;
    padding: .7rem .75rem; border-radius: 10px; cursor: pointer;
    transition: background .15s; border-bottom: 1px solid var(--border);
  }
  .stream-item:last-child { border-bottom: none; }
  .stream-item:hover { background: rgba(167,139,250,.09); }
  .stream-item-main { flex: 1; min-width: 0; }
  .stream-item-name { font-size: .9rem; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .stream-item-song { font-size: .75rem; color: var(--muted); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; margin-top: .15rem; }
  .stream-item-meta { display: flex; flex-direction: column; align-items: flex-end; gap: .2rem; flex-shrink: 0; }
  .stream-item-bitrate { font-size: .72rem; color: var(--accent-light); font-weight: 700; }
  .stream-play-hint { font-size: .7rem; color: var(--muted); }

  /* Loading / empty states */
  .dir-state {
    display: flex; flex-direction: column; align-items: center;
    justify-content: center; padding: 3rem 1rem; color: var(--muted);
    gap: .75rem;
  }
  .dir-state .spinner {
    width: 28px; height: 28px; border: 3px solid var(--border);
    border-top-color: var(--accent-light); border-radius: 50%;
    animation: spin .8s linear infinite;
  }
  @keyframes spin { to { transform: rotate(360deg); } }
</style>
</head>
<body>

<header>
  <div class="logo-group">
    <span>📻</span>
    <h1>RadioResurrector</h1>
  </div>
  <form action="/logout" method="post">
    <button class="logout" type="submit">Logout</button>
  </form>
</header>

<div class="dashboard-grid">

  <!-- ══ LEFT COLUMN — controls ══ -->
  <div class="col-left">

    <!-- ── Now Playing (+ stream selector) ── -->
    <div class="now-playing">
      <div class="np-top">
        <span class="np-badge {{ state.mode }}" id="npBadge">
          <span class="pulse"></span>
          <span id="npMode">{{ state.mode | upper }}</span>
        </span>
        <span class="np-duration" id="npDuration">—</span>
      </div>

      <div class="np-title" id="npTitle">
        {% if state.mode in ('live', 'starting') %}{{ state.name or state.url }}
        {% elif state.mode in ('buffer', 'forced') %}Buffer Playback
        {% else %}—{% endif %}
      </div>
      <div class="np-subtitle" id="npSubtitle">
        {% if state.mode in ('live', 'starting') %}{{ state.url }}
        {% elif state.mode in ('buffer', 'forced') %}
          {{ buf.chunk_count }} chunks &middot; {{ (buf.covers_seconds // 60) }} min &middot; {{ '%.1f' % (buf.total_bytes / 1048576) }} MB on disk
        {% endif %}
      </div>

      <div class="svc-row">
        <div class="dot {{ svc_status }}" id="svcDot"></div>
        <span class="svc-label" id="svcLabel">radio.service — {{ svc_status }}</span>
      </div>

      <!-- Stream selector lives here, next to the status -->
      <div class="card-title" style="margin-bottom:.6rem">📡 Stream</div>
      <div class="stream-row" style="margin-bottom:1rem">
        <select id="presetSelect" onchange="applyPreset()">
          <option value="">— Preset —</option>
          {% for s in cfg.streams %}
          <option value="{{ s.url }}">{{ s.name }}</option>
          {% endfor %}
        </select>
        <input type="text" id="streamUrl" value="{{ cfg.stream_url }}"
               placeholder="https://stream.example.com/live">
        <button class="btn-browse" onclick="openDirectory()" title="Browse Icecast directory">
          Browse
        </button>
      </div>

      <!-- Mode switch button -->
      {% if state.mode in ('buffer', 'forced') %}
      <button class="btn-mode to-live" id="modeBtn" onclick="switchMode('live')">
        ↑ Resume Live Stream
      </button>
      {% else %}
      <button class="btn-mode to-buffer" id="modeBtn" onclick="switchMode('buffer')">
        ↓ Switch to Buffer
      </button>
      {% endif %}
    </div>

    <!-- ── Volume ── -->
    <div class="card">
      <div class="card-title">🔊 Volume</div>
      <div class="slider-row">
        <div class="slider-header">
          <span class="slider-label">Output Level</span>
          <span class="slider-value" id="volDisplay">{{ cfg.volume }}%</span>
        </div>
        <input type="range" id="volumeSlider" min="0" max="100" value="{{ cfg.volume }}" step="1">
      </div>
    </div>

    <!-- ── Recording Settings ── -->
    <div class="card">
      <div class="card-title">⏺ Recording Settings</div>
      <div class="slider-row">
        <div class="slider-header">
          <span class="slider-label">Chunk Size</span>
          <span class="slider-value" id="chunkDisplay">{{ cfg.chunk_seconds }}s</span>
        </div>
        <input type="range" id="chunkSlider" min="60" max="600" value="{{ cfg.chunk_seconds }}" step="30"
               oninput="document.getElementById('chunkDisplay').textContent=this.value+'s'">
      </div>
      <div class="slider-row">
        <div class="slider-header">
          <span class="slider-label">Buffer Duration</span>
          <span class="slider-value" id="bufferDisplay">{{ cfg.buffer_minutes }}m</span>
        </div>
        <input type="range" id="bufferSlider" min="30" max="360" value="{{ cfg.buffer_minutes }}" step="30"
               oninput="document.getElementById('bufferDisplay').textContent=this.value+'m'">
      </div>
      <div class="slider-row">
        <div class="slider-header">
          <span class="slider-label">Check Interval</span>
          <span class="slider-value" id="intervalDisplay">{{ cfg.check_interval }}s</span>
        </div>
        <input type="range" id="intervalSlider" min="5" max="60" value="{{ cfg.check_interval }}" step="5"
               oninput="document.getElementById('intervalDisplay').textContent=this.value+'s'">
      </div>
    </div>

    <!-- ── Apply ── -->
    <div class="card">
      <div class="card-title">Apply Changes</div>
      <p style="font-size:.85rem;color:var(--muted);margin-bottom:1rem;">
        Saves all settings and restarts the radio service.
      </p>
      <button class="btn btn-primary" style="width:100%" onclick="applySettings()">Apply &amp; Restart</button>
    </div>

    <!-- ── Service Controls ── -->
    <div class="card">
      <div class="card-title">⚙ Service</div>
      <div class="btn-row">
        <button class="btn btn-success" onclick="serviceAction('start')">Start</button>
        <button class="btn btn-ghost" onclick="serviceAction('restart')">Restart</button>
        <button class="btn btn-danger" onclick="serviceAction('stop')">Stop</button>
      </div>
    </div>

    <!-- ── Stream Presets ── -->
    <div class="card">
      <div class="card-title">📋 Stream Presets</div>
      <ul class="preset-list" id="presetList">
        {% for s in cfg.streams %}
        <li class="preset-item" data-url="{{ s.url }}">
          <span class="preset-name">{{ s.name }}</span>
          <span class="preset-url">{{ s.url }}</span>
          <button class="btn btn-sm btn-danger" onclick="removePreset('{{ s.url }}')">✕</button>
        </li>
        {% endfor %}
      </ul>
      <div class="add-preset-row">
        <input type="text" id="newPresetName" placeholder="Name">
        <input type="text" id="newPresetUrl" placeholder="Stream URL">
        <button class="btn btn-sm btn-primary" onclick="addPreset()">Add</button>
      </div>
    </div>

    <!-- ── Change PIN ── -->
    <div class="card">
      <div class="card-title">🔒 Change PIN</div>
      <div class="pin-row">
        <input type="password" id="newPin" inputmode="numeric" pattern="[0-9]*"
               maxlength="8" placeholder="New PIN">
        <button class="btn btn-primary btn-sm" onclick="changePin()">Save PIN</button>
      </div>
    </div>

  </div><!-- /col-left -->

  <!-- ══ RIGHT COLUMN — monitoring ══ -->
  <div class="col-right">

    <!-- ── Log Terminal ── -->
    <div class="terminal-card">
      <div class="terminal-header">
        <span class="terminal-title">⬛ radio.service log</span>
        <div class="terminal-actions">
          <button class="btn-tiny" id="scrollLockBtn" onclick="toggleScrollLock()">Auto-scroll ✓</button>
          <button class="btn-tiny" onclick="clearLog()">Clear</button>
        </div>
      </div>
      <div class="log-body" id="logBody"></div>
    </div>

    <!-- ── Buffer Monitor ── -->
    <div class="card">
      <div class="card-title">📼 Buffer</div>
      <div class="buf-stats">
        <div class="buf-stat">
          <span class="buf-stat-val" id="bChunks">{{ buf.chunk_count }}</span>
          <span class="buf-stat-lbl">chunks</span>
        </div>
        <div class="buf-stat">
          <span class="buf-stat-val" id="bCovers">{{ (buf.covers_seconds // 60) }}m</span>
          <span class="buf-stat-lbl">covered</span>
        </div>
        <div class="buf-stat">
          <span class="buf-stat-val" id="bSize">{{ '%.1f' % (buf.total_bytes / 1048576) }}MB</span>
          <span class="buf-stat-lbl">on disk</span>
        </div>
      </div>
      <div class="fill-bar-wrap">
        <div class="fill-bar-inner" id="fillBar"
             style="width:{{ [100, buf.chunk_count * 100 // [buf.max_chunks,1]|max]|min }}%"></div>
      </div>
      <div class="fill-bar-label">
        <span id="fillLabel">{{ buf.chunk_count }} / {{ buf.max_chunks }} chunks</span>
        <span id="fillPct">{{ [100, buf.chunk_count * 100 // [buf.max_chunks,1]|max]|min }}%</span>
      </div>
      <div class="chunk-list-wrap">
        <table class="chunk-list">
          <thead><tr><th>File</th><th>Size</th><th>Age</th></tr></thead>
          <tbody id="chunkTable">
            {% for f in buf.files | reverse %}
            <tr>
              <td>{{ f.name }}</td>
              <td class="dim">{{ '%.1f' % (f.size / 1048576) }} MB</td>
              <td class="dim right" data-ts="{{ f.mtime }}">—</td>
            </tr>
            {% else %}
            <tr><td colspan="3" class="dim" style="text-align:center;padding:1rem">No buffer files</td></tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <button class="btn btn-danger btn-sm" onclick="confirmClear()">Clear Buffer</button>
    </div>

  </div><!-- /col-right -->

</div><!-- /dashboard-grid -->

<!-- ── Icecast Directory Panel ── -->
<div class="dir-overlay" id="dirOverlay">
  <div class="dir-panel">
    <div class="dir-header">
      <h2>📻 Icecast Directory</h2>
      <input class="dir-search" id="dirSearch" type="text"
             placeholder="Filter…" oninput="filterDir()">
      <button class="dir-close" onclick="closeDirectory()">✕ Close</button>
    </div>
    <div class="dir-breadcrumb" id="dirCrumb">
      <span>All Genres</span>
    </div>
    <div class="dir-body" id="dirBody">
      <div class="dir-state"><span>Loading…</span></div>
    </div>
  </div>
</div>

<!-- Clear Buffer confirmation -->
<div class="overlay" id="clearOverlay">
  <div class="dialog">
    <h2>Clear buffer?</h2>
    <p>Deletes all cached audio. If the live stream is down, playback will stop until new chunks are recorded.</p>
    <div class="btn-row">
      <button class="btn btn-ghost" onclick="closeClear()">Cancel</button>
      <button class="btn btn-danger" onclick="doClear()">Clear</button>
    </div>
  </div>
</div>

<div id="toast"></div>

<script>
// ── Toast ──
function toast(msg, isError=false) {
  const t = document.getElementById('toast');
  t.textContent = msg;
  t.className = 'show' + (isError ? ' error' : '');
  clearTimeout(window._toastTimer);
  window._toastTimer = setTimeout(() => t.className = '', 2600);
}

// ── Duration ticker ──
let npSince = {{ state.since or 0 }};
function durSince(ts) {
  if (!ts) return '—';
  const s = Math.max(0, Math.floor(Date.now()/1000) - ts);
  if (s < 60)   return s + 's';
  if (s < 3600) return Math.floor(s/60) + 'm ' + (s%60) + 's';
  return Math.floor(s/3600) + 'h ' + Math.floor((s%3600)/60) + 'm';
}
setInterval(() => { document.getElementById('npDuration').textContent = durSince(npSince); }, 1000);

// ── Relative time for chunk ages ──
function relTime(ts) {
  const s = Math.floor(Date.now()/1000) - ts;
  if (s < 60)   return s + 's ago';
  if (s < 3600) return Math.floor(s/60) + 'm ago';
  return Math.floor(s/3600) + 'h ago';
}
function refreshAgeCells() {
  document.querySelectorAll('[data-ts]').forEach(td => {
    td.textContent = relTime(parseInt(td.dataset.ts));
  });
}
setInterval(refreshAgeCells, 10000);
refreshAgeCells();

// ── Log terminal ──
const logBody = document.getElementById('logBody');
let autoScroll = true;
let lineCount  = 0;
const MAX_LINES = 300;

function toggleScrollLock() {
  autoScroll = !autoScroll;
  document.getElementById('scrollLockBtn').textContent =
    autoScroll ? 'Auto-scroll ✓' : 'Auto-scroll ✗';
}
function clearLog() { logBody.innerHTML = ''; lineCount = 0; }

function classifyLine(line) {
  const l = line.toLowerCase();
  if (l.includes('error') || l.includes('failed') || l.includes('fail') || l.includes('exiting')) return 'log-err';
  if (l.includes('down') || l.includes('buffer') || l.includes('backup') || l.includes('force')) return 'log-warn';
  if (l.includes('stream ok') || l.includes('live') || l.includes('detected')) return 'log-ok';
  return 'log-info';
}

function appendLog(raw) {
  // Split the journalctl prefix (timestamp + host + unit) from the message
  // Format: "Apr 14 21:52:43 raspberrypi radio.sh[1266]: [radio] ..."
  const match = raw.match(/^(\w{3}\s+\d+\s+[\d:]+\s+\S+\s+\S+\[\d+\]:\s*)(.*)/);
  let prefix = '', msg = raw;
  if (match) { prefix = match[1]; msg = match[2]; }

  const div = document.createElement('div');
  div.className = 'log-line ' + classifyLine(msg);
  div.innerHTML = (prefix ? `<span class="log-dim">${esc(prefix)}</span>` : '') + esc(msg);
  logBody.appendChild(div);
  lineCount++;

  // Trim oldest lines
  while (lineCount > MAX_LINES) {
    logBody.removeChild(logBody.firstChild);
    lineCount--;
  }

  if (autoScroll) logBody.scrollTop = logBody.scrollHeight;
}

// Connect SSE
function connectSSE() {
  const es = new EventSource('/logs');
  es.onmessage = e => { try { appendLog(JSON.parse(e.data)); } catch {} };
  es.onerror = () => { setTimeout(connectSSE, 5000); es.close(); };
}
connectSSE();

// ── Mode switch ──
function switchMode(mode) {
  api('/mode', { mode })
    .then(() => { toast(mode === 'buffer' ? 'Switching to buffer…' : 'Resuming live stream…'); })
    .catch(() => toast('Mode switch failed', true));
}

// ── Update Now Playing ──
function updateNP(state, buf) {
  // Badge
  const badge = document.getElementById('npBadge');
  const modeEl = document.getElementById('npMode');
  badge.className = 'np-badge ' + state.mode;
  modeEl.textContent = state.mode.toUpperCase();
  npSince = state.since || 0;

  // Title + subtitle
  const titleEl    = document.getElementById('npTitle');
  const subtitleEl = document.getElementById('npSubtitle');
  if (state.mode === 'live' || state.mode === 'starting') {
    titleEl.textContent    = state.name || state.url || '—';
    subtitleEl.textContent = state.url || '';
  } else if (state.mode === 'buffer' || state.mode === 'forced') {
    titleEl.textContent    = 'Buffer Playback';
    const mins = Math.floor((buf.covers_seconds || 0) / 60);
    const mb   = ((buf.total_bytes || 0) / 1048576).toFixed(1);
    subtitleEl.textContent = `${buf.chunk_count} chunks · ${mins} min · ${mb} MB on disk`;
  } else {
    titleEl.textContent = '—'; subtitleEl.textContent = '';
  }

  // Mode button
  const btn = document.getElementById('modeBtn');
  if (state.mode === 'buffer' || state.mode === 'forced') {
    btn.className = 'btn-mode to-live';
    btn.textContent = '↑ Resume Live Stream';
    btn.onclick = () => switchMode('live');
  } else {
    btn.className = 'btn-mode to-buffer';
    btn.textContent = '↓ Switch to Buffer';
    btn.onclick = () => switchMode('buffer');
  }
}

function updateSvc(status) {
  document.getElementById('svcDot').className   = 'dot ' + status;
  document.getElementById('svcLabel').textContent = 'radio.service — ' + status;
}

function updateBuffer(buf) {
  document.getElementById('bChunks').textContent = buf.chunk_count;
  document.getElementById('bCovers').textContent = Math.floor(buf.covers_seconds/60) + 'm';
  document.getElementById('bSize').textContent   = (buf.total_bytes/1048576).toFixed(1) + 'MB';

  const pct = buf.max_chunks ? Math.min(100, Math.round(buf.chunk_count*100/buf.max_chunks)) : 0;
  document.getElementById('fillBar').style.width    = pct + '%';
  document.getElementById('fillLabel').textContent  = `${buf.chunk_count} / ${buf.max_chunks} chunks`;
  document.getElementById('fillPct').textContent    = pct + '%';

  const tbody = document.getElementById('chunkTable');
  if (!buf.files.length) {
    tbody.innerHTML = '<tr><td colspan="3" class="dim" style="text-align:center;padding:1rem">No buffer files</td></tr>';
    return;
  }
  tbody.innerHTML = [...buf.files].reverse().map(f =>
    `<tr><td>${esc(f.name)}</td>
     <td class="dim">${(f.size/1048576).toFixed(1)} MB</td>
     <td class="dim right" data-ts="${f.mtime}">${relTime(f.mtime)}</td></tr>`
  ).join('');
}

// ── Poll every 8 s ──
function poll() {
  fetch('/status').then(r => r.json()).then(d => {
    updateNP(d.state, d.buffer);
    updateSvc(d.svc_status);
    updateBuffer(d.buffer);
  }).catch(() => {});
}
setInterval(poll, 8000);

// ── Volume ──
const volSlider  = document.getElementById('volumeSlider');
const volDisplay = document.getElementById('volDisplay');
let volTimer;
volSlider.addEventListener('input', () => {
  volDisplay.textContent = volSlider.value + '%';
  clearTimeout(volTimer);
  volTimer = setTimeout(() => {
    api('/volume', { volume: parseInt(volSlider.value) })
      .then(() => toast('Volume → ' + volSlider.value + '%'))
      .catch(() => toast('Volume update failed', true));
  }, 400);
});

// ── Apply settings ──
function applySettings() {
  const payload = {
    stream_url:     document.getElementById('streamUrl').value.trim(),
    chunk_seconds:  parseInt(document.getElementById('chunkSlider').value),
    buffer_minutes: parseInt(document.getElementById('bufferSlider').value),
    check_interval: parseInt(document.getElementById('intervalSlider').value),
    volume:         parseInt(volSlider.value),
  };
  if (!payload.stream_url) return toast('Stream URL is required', true);
  api('/apply', payload)
    .then(() => toast('Settings saved — restarting service'))
    .catch(() => toast('Failed to apply settings', true));
}

// ── Service actions ──
function serviceAction(action) {
  api('/service/' + action, {})
    .then(d => { toast('Service ' + action + 'ed'); updateSvc(d.status); })
    .catch(() => toast('Service action failed', true));
}

// ── Clear buffer ──
function confirmClear() { document.getElementById('clearOverlay').classList.add('open'); }
function closeClear()   { document.getElementById('clearOverlay').classList.remove('open'); }
function doClear() {
  closeClear();
  api('/buffer/clear', {})
    .then(d => { toast('Buffer cleared'); updateBuffer(d.buffer); })
    .catch(() => toast('Failed to clear buffer', true));
}

// ── Presets ──
function applyPreset() {
  const sel = document.getElementById('presetSelect');
  if (sel.value) document.getElementById('streamUrl').value = sel.value;
  sel.value = '';
}
function addPreset() {
  const name = document.getElementById('newPresetName').value.trim();
  const url  = document.getElementById('newPresetUrl').value.trim();
  if (!name || !url) return toast('Name and URL are required', true);
  api('/presets/add', { name, url }).then(() => {
    toast('Preset added');
    document.getElementById('newPresetName').value = '';
    document.getElementById('newPresetUrl').value  = '';
    const li = document.createElement('li');
    li.className = 'preset-item'; li.dataset.url = url;
    li.innerHTML = `<span class="preset-name">${esc(name)}</span>
      <span class="preset-url">${esc(url)}</span>
      <button class="btn btn-sm btn-danger" onclick="removePreset('${esc(url)}')">✕</button>`;
    document.getElementById('presetList').appendChild(li);
    const opt = document.createElement('option');
    opt.value = url; opt.textContent = name;
    document.getElementById('presetSelect').appendChild(opt);
  }).catch(() => toast('Failed to add preset', true));
}
function removePreset(url) {
  api('/presets/remove', { url }).then(() => {
    toast('Preset removed');
    const item = document.querySelector(`[data-url="${CSS.escape(url)}"]`);
    if (item) item.remove();
    const opt = document.querySelector(`#presetSelect option[value="${CSS.escape(url)}"]`);
    if (opt) opt.remove();
  }).catch(() => toast('Failed to remove preset', true));
}

// ── PIN ──
function changePin() {
  const pin = document.getElementById('newPin').value.trim();
  if (!/^\d{4,8}$/.test(pin)) return toast('PIN must be 4–8 digits', true);
  api('/pin', { pin }).then(() => {
    toast('PIN updated'); document.getElementById('newPin').value = '';
  }).catch(() => toast('Failed to update PIN', true));
}

// ── Icecast Directory ──
let _dirGenres    = null;   // [{name, count}]
let _dirStreams    = null;   // [{name, url, bitrate, song}] for current genre
let _dirGenre     = null;   // currently selected genre name
let _dirLoaded    = false;

function openDirectory() {
  document.getElementById('dirOverlay').classList.add('open');
  document.getElementById('dirSearch').value = '';
  if (!_dirLoaded) loadGenres();
}
function closeDirectory() {
  document.getElementById('dirOverlay').classList.remove('open');
}

function loadGenres() {
  showDirLoading();
  fetch('/directory/genres')
    .then(r => r.json())
    .then(d => {
      if (d.error) throw new Error(d.error);
      _dirGenres = d.genres;
      _dirLoaded = true;
      _dirGenre  = null;
      _dirStreams = null;
      showGenres(_dirGenres);
    })
    .catch(e => showDirError(e.message));
}

function loadStreams(genreName) {
  _dirGenre = genreName;
  showDirLoading();
  fetch('/directory/streams?' + new URLSearchParams({genre: genreName}))
    .then(r => r.json())
    .then(d => {
      if (d.error) throw new Error(d.error);
      _dirStreams = d.streams;
      showStreams(_dirStreams);
    })
    .catch(e => showDirError(e.message));
}

function filterDir() {
  const q = document.getElementById('dirSearch').value.trim().toLowerCase();
  if (_dirGenre) {
    // filter streams
    const filtered = q ? _dirStreams.filter(s =>
      s.name.toLowerCase().includes(q) || s.song.toLowerCase().includes(q)
    ) : _dirStreams;
    showStreams(filtered, false);
  } else {
    // filter genres
    const filtered = q ? (_dirGenres || []).filter(g =>
      g.name.toLowerCase().includes(q)
    ) : _dirGenres;
    showGenres(filtered, false);
  }
}

function showGenres(genres, updateCrumb=true) {
  if (updateCrumb) {
    document.getElementById('dirCrumb').innerHTML = '<span>All Genres</span>';
  }
  if (!genres || !genres.length) {
    document.getElementById('dirBody').innerHTML =
      '<div class="dir-state"><span>No genres found</span></div>';
    return;
  }
  document.getElementById('dirBody').innerHTML =
    '<div class="genre-grid">' +
    genres.map(g =>
      `<div class="genre-tile" onclick="loadStreams(${JSON.stringify(g.name)})">
        <div class="genre-tile-name">${esc(g.name)}</div>
        <div class="genre-tile-count">${g.count} stream${g.count !== 1 ? 's' : ''}</div>
      </div>`
    ).join('') +
    '</div>';
}

function showStreams(streams, updateCrumb=true) {
  if (updateCrumb) {
    document.getElementById('dirCrumb').innerHTML =
      `<button class="dir-crumb-btn" onclick="backToGenres()">← Genres</button>
       <span>/</span>
       <span>${esc(_dirGenre)}</span>
       <span style="color:var(--muted);margin-left:auto">${streams.length} streams</span>`;
  }
  if (!streams.length) {
    document.getElementById('dirBody').innerHTML =
      '<div class="dir-state"><span>No streams found</span></div>';
    return;
  }
  document.getElementById('dirBody').innerHTML =
    '<ul class="stream-list">' +
    streams.map(s =>
      `<li class="stream-item" onclick="playDirectoryStream(${JSON.stringify(s.name)}, ${JSON.stringify(s.url)})">
        <div class="stream-item-main">
          <div class="stream-item-name">${esc(s.name)}</div>
          ${s.song ? `<div class="stream-item-song">♪ ${esc(s.song)}</div>` : ''}
        </div>
        <div class="stream-item-meta">
          ${s.bitrate ? `<span class="stream-item-bitrate">${esc(s.bitrate)}k</span>` : ''}
          <span class="stream-play-hint">▶ Play</span>
        </div>
      </li>`
    ).join('') +
    '</ul>';
}

function backToGenres() {
  _dirGenre = null; _dirStreams = null;
  document.getElementById('dirSearch').value = '';
  showGenres(_dirGenres);
}

function showDirLoading() {
  document.getElementById('dirBody').innerHTML =
    '<div class="dir-state"><div class="spinner"></div><span>Loading…</span></div>';
}
function showDirError(msg) {
  document.getElementById('dirBody').innerHTML =
    `<div class="dir-state"><span style="color:var(--red)">Error: ${esc(msg)}</span></div>`;
}

function playDirectoryStream(name, url) {
  closeDirectory();
  document.getElementById('streamUrl').value = url;
  const payload = {
    stream_url:     url,
    chunk_seconds:  parseInt(document.getElementById('chunkSlider').value),
    buffer_minutes: parseInt(document.getElementById('bufferSlider').value),
    check_interval: parseInt(document.getElementById('intervalSlider').value),
    volume:         parseInt(document.getElementById('volumeSlider').value),
  };
  api('/apply', payload)
    .then(() => toast('▶ Now playing: ' + name))
    .catch(() => toast('Failed to switch stream', true));
}

// ── Escape ──
function esc(s) {
  return String(s)
    .replace(/&/g,'&amp;').replace(/</g,'&lt;')
    .replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

// ── API helper ──
function api(path, body) {
  return fetch(path, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  }).then(r => { if (!r.ok) throw new Error(r.status); return r.json(); });
}
</script>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

def require_auth():
    return session.get("authed") is True


@app.route("/", methods=["GET", "POST"])
def index():
    if require_auth():
        return redirect(url_for("dashboard"))
    if request.method == "POST":
        cfg = load_config()
        if request.form.get("pin") == cfg["pin"]:
            session["authed"] = True
            return redirect(url_for("dashboard"))
        return render_template_string(PIN_PAGE, error="Incorrect PIN — try again")
    return render_template_string(PIN_PAGE, error=None)


@app.route("/dashboard")
def dashboard():
    if not require_auth():
        return redirect(url_for("index"))
    cfg = load_config()
    return render_template_string(
        MAIN_PAGE,
        cfg=cfg,
        state=playback_state(),
        svc_status=service_status(),
        buf=buffer_info(),
    )


@app.route("/logout", methods=["POST"])
def logout():
    session.clear()
    return redirect(url_for("index"))


@app.route("/logs")
def stream_logs():
    """Server-Sent Events stream of journalctl output for radio.service."""
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401

    def generate():
        proc = subprocess.Popen(
            ["journalctl", "-fu", "radio.service", "--no-pager", "-n", "80",
             "--output=short"],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        try:
            for line in proc.stdout:
                line = line.rstrip()
                if line:
                    yield f"data: {json.dumps(line)}\n\n"
        except GeneratorExit:
            pass
        finally:
            proc.kill()
            proc.wait()

    return Response(
        generate(),
        mimetype="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.route("/status")
def get_status():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    return jsonify({
        "svc_status": service_status(),
        "state":      playback_state(),
        "buffer":     buffer_info(),
    })


@app.route("/mode", methods=["POST"])
def set_mode():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    mode = request.get_json(force=True).get("mode", "")
    if mode == "buffer":
        open(FORCE_BUFFER, "w").close()
        subprocess.run(["systemctl", "restart", "radio.service"], timeout=10)
    elif mode == "live":
        try:
            os.remove(FORCE_BUFFER)
        except FileNotFoundError:
            pass
        subprocess.run(["systemctl", "restart", "radio.service"], timeout=10)
    else:
        return jsonify({"error": "mode must be 'live' or 'buffer'"}), 400
    return jsonify({"ok": True})


@app.route("/apply", methods=["POST"])
def apply():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    data = request.get_json(force=True)
    cfg = load_config()
    cfg["stream_url"]     = str(data.get("stream_url", cfg["stream_url"]))
    cfg["chunk_seconds"]  = max(60,  min(600, int(data.get("chunk_seconds",  cfg["chunk_seconds"]))))
    cfg["buffer_minutes"] = max(30,  min(360, int(data.get("buffer_minutes", cfg["buffer_minutes"]))))
    cfg["check_interval"] = max(5,   min(60,  int(data.get("check_interval", cfg["check_interval"]))))
    cfg["volume"]         = max(0,   min(100, int(data.get("volume",         cfg["volume"]))))
    save_config(cfg)
    subprocess.run(["systemctl", "restart", "radio.service"], timeout=10)
    return jsonify({"ok": True})


@app.route("/volume", methods=["POST"])
def set_volume():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    vol = max(0, min(100, int(request.get_json(force=True).get("volume", 90))))
    subprocess.run(["amixer", "sset", "PCM", f"{vol}%"], capture_output=True)
    cfg = load_config()
    cfg["volume"] = vol
    save_config(cfg)
    return jsonify({"ok": True, "volume": vol})


@app.route("/service/<action>", methods=["POST"])
def service_action(action):
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    if action not in ("start", "stop", "restart"):
        return jsonify({"error": "invalid action"}), 400
    subprocess.run(["systemctl", action, "radio.service"], timeout=10)
    return jsonify({"ok": True, "status": service_status()})


@app.route("/buffer/clear", methods=["POST"])
def clear_buffer():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    try:
        for name in os.listdir(BUFFER_DIR):
            if name.endswith(".mp3") or name.endswith(".m3u"):
                os.remove(os.path.join(BUFFER_DIR, name))
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True, "buffer": buffer_info()})


@app.route("/presets/add", methods=["POST"])
def add_preset():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    data = request.get_json(force=True)
    name = str(data.get("name", "")).strip()[:64]
    url  = str(data.get("url",  "")).strip()[:512]
    if not name or not url:
        return jsonify({"error": "name and url required"}), 400
    cfg = load_config()
    cfg["streams"] = [s for s in cfg.get("streams", []) if s["url"] != url]
    cfg["streams"].append({"name": name, "url": url})
    save_config(cfg)
    return jsonify({"ok": True})


@app.route("/presets/remove", methods=["POST"])
def remove_preset():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    url = str(request.get_json(force=True).get("url", "")).strip()
    cfg = load_config()
    cfg["streams"] = [s for s in cfg.get("streams", []) if s["url"] != url]
    save_config(cfg)
    return jsonify({"ok": True})


@app.route("/pin", methods=["POST"])
def change_pin():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    pin = str(request.get_json(force=True).get("pin", "")).strip()
    if not pin.isdigit() or not (4 <= len(pin) <= 8):
        return jsonify({"error": "PIN must be 4–8 digits"}), 400
    cfg = load_config()
    cfg["pin"] = pin
    save_config(cfg)
    return jsonify({"ok": True})


@app.route("/directory/genres")
def dir_genres():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    try:
        data = fetch_yp()
        return jsonify({"genres": data["genres"]})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/directory/streams")
def dir_streams():
    if not require_auth():
        return jsonify({"error": "unauthorized"}), 401
    genre = request.args.get("genre", "")
    try:
        data = fetch_yp()
        streams = data["by_genre"].get(genre, [])
        return jsonify({"streams": streams})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080, debug=False, threaded=True)
